fun main() {
    println("Module: Set")
    println("")
    println("Imports:")
    println(" - List")
    println("")
    println("Space: Element : Element")
    println("")
    println("")
    println("Space: SuperSet : Element")
    println("")
    println("")
    println("Space: Set : Element extends SuperSet")
    println("")
    println("")
    println("Operator: union : Set -> Set -> Set")
    println(" - associative")
    println(" - id : ∅")
    println("")
    println("")
    println("")
    println("Operator: isIn : Element -> Set -> Bool")
    println("")
    println("")
    println("Operator: implication : Bool -> Bool -> Bool")
    println("")
    println("")
    println("Operator: negation : Bool -> Bool")
    println("")
    println("")
    println("Operator: disjunction : Bool -> Bool -> Bool")
    println("")
    println("")
    println("Variables:")
    println(" - p: Bool")
    println(" - q: Bool")
    println("")
    println("")
    println("Rule: (implication p q) -> (disjunction (negation p) q)")
    println("")
    println("")
    println("Expression: (forall x in Element . (forall S in Set . (forall U in Set . x isIn (union S U))))")
}
